// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg4rrWhDF6-UoF4z5m5Gf7_DL1uPTM9aw',
    appId: '1:971568197406:web:b6fb8e17f859438c0ae30f',
    messagingSenderId: '971568197406',
    projectId: 'tripy-tropi',
    authDomain: 'tripy-tropi.firebaseapp.com',
    storageBucket: 'tripy-tropi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVaPKSrUKpep719Im4AIlLGfHinVYDud4',
    appId: '1:971568197406:android:08357f29d484bde70ae30f',
    messagingSenderId: '971568197406',
    projectId: 'tripy-tropi',
    storageBucket: 'tripy-tropi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbZ4Nz35NBxglb2u5EjsV7j8ELuakPjMk',
    appId: '1:971568197406:ios:b2354a8df23d55710ae30f',
    messagingSenderId: '971568197406',
    projectId: 'tripy-tropi',
    storageBucket: 'tripy-tropi.firebasestorage.app',
    iosBundleId: 'com.example.tripyTropy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbZ4Nz35NBxglb2u5EjsV7j8ELuakPjMk',
    appId: '1:971568197406:ios:b2354a8df23d55710ae30f',
    messagingSenderId: '971568197406',
    projectId: 'tripy-tropi',
    storageBucket: 'tripy-tropi.firebasestorage.app',
    iosBundleId: 'com.example.tripyTropy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg4rrWhDF6-UoF4z5m5Gf7_DL1uPTM9aw',
    appId: '1:971568197406:web:e5fa5fb081210f270ae30f',
    messagingSenderId: '971568197406',
    projectId: 'tripy-tropi',
    authDomain: 'tripy-tropi.firebaseapp.com',
    storageBucket: 'tripy-tropi.firebasestorage.app',
  );
}
